services: 
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: transcript-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guirra
      RABBITMQ_DEFAULT_PASS: mguirra085213
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: transcript-pg-db
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: guirra
      POSTGRES_PASSWORD: mguirra085213.
      POSTGRES_DB: transcript-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: